# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='manager.proto',
  package='drago.services.collector',
  syntax='proto3',
  serialized_pb=_b('\n\rmanager.proto\x12\x18\x64rago.services.collector\"\xdb\x01\n\x10RegistrationInfo\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x32\n\x07network\x18\x02 \x01(\x0e\x32!.drago.services.collector.Network\x12\x42\n\x10\x63ollection_types\x18\x03 \x03(\x0e\x32(.drago.services.collector.CollectionType\x12\x42\n\x10\x63ollection_modes\x18\x04 \x03(\x0e\x32(.drago.services.collector.CollectionMode\"\x16\n\x14RegistrationResponse*Y\n\x07Network\x12\x15\n\x11UNDEFINED_NETWORK\x10\x00\x12\x07\n\x03WEB\x10\x01\x12\x0b\n\x07TWITTER\x10\x02\x12\x0c\n\x08\x46\x41\x43\x45\x42OOK\x10\x03\x12\x06\n\x02VK\x10\x04\x12\x0b\n\x07YOUTUBE\x10\x05*O\n\x0e\x43ollectionType\x12\x12\n\x0eUNDEFINED_TYPE\x10\x00\x12\x0b\n\x07KEYWORD\x10\x01\x12\x07\n\x03URL\x10\x02\x12\n\n\x06\x45NTITY\x10\x03\x12\x07\n\x03GEO\x10\x04*@\n\x0e\x43ollectionMode\x12\x12\n\x0eUNDEFINED_MODE\x10\x00\x12\x0b\n\x07POLLING\x10\x01\x12\r\n\tSTREAMING\x10\x02\x32\xc5\x02\n\x07Manager\x12\x66\n\x08Register\x12*.drago.services.collector.RegistrationInfo\x1a..drago.services.collector.RegistrationResponse\x12h\n\nUnregister\x12*.drago.services.collector.RegistrationInfo\x1a..drago.services.collector.RegistrationResponse\x12h\n\nInitialize\x12*.drago.services.collector.RegistrationInfo\x1a..drago.services.collector.RegistrationResponseBm\n\"com.qntfy.drago.services.collectorB\x16\x44GORegistrationServiceH\x01P\x01Z%gitlab.qntfy.com/qcr/drago/collection\xa2\x02\x03\x44GOb\x06proto3')
)

_NETWORK = _descriptor.EnumDescriptor(
  name='Network',
  full_name='drago.services.collector.Network',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED_NETWORK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEB', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TWITTER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACEBOOK', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VK', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YOUTUBE', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=289,
  serialized_end=378,
)
_sym_db.RegisterEnumDescriptor(_NETWORK)

Network = enum_type_wrapper.EnumTypeWrapper(_NETWORK)
_COLLECTIONTYPE = _descriptor.EnumDescriptor(
  name='CollectionType',
  full_name='drago.services.collector.CollectionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED_TYPE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KEYWORD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='URL', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTITY', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEO', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=380,
  serialized_end=459,
)
_sym_db.RegisterEnumDescriptor(_COLLECTIONTYPE)

CollectionType = enum_type_wrapper.EnumTypeWrapper(_COLLECTIONTYPE)
_COLLECTIONMODE = _descriptor.EnumDescriptor(
  name='CollectionMode',
  full_name='drago.services.collector.CollectionMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED_MODE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POLLING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STREAMING', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=461,
  serialized_end=525,
)
_sym_db.RegisterEnumDescriptor(_COLLECTIONMODE)

CollectionMode = enum_type_wrapper.EnumTypeWrapper(_COLLECTIONMODE)
UNDEFINED_NETWORK = 0
WEB = 1
TWITTER = 2
FACEBOOK = 3
VK = 4
YOUTUBE = 5
UNDEFINED_TYPE = 0
KEYWORD = 1
URL = 2
ENTITY = 3
GEO = 4
UNDEFINED_MODE = 0
POLLING = 1
STREAMING = 2



_REGISTRATIONINFO = _descriptor.Descriptor(
  name='RegistrationInfo',
  full_name='drago.services.collector.RegistrationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='drago.services.collector.RegistrationInfo.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='network', full_name='drago.services.collector.RegistrationInfo.network', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collection_types', full_name='drago.services.collector.RegistrationInfo.collection_types', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collection_modes', full_name='drago.services.collector.RegistrationInfo.collection_modes', index=3,
      number=4, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=263,
)


_REGISTRATIONRESPONSE = _descriptor.Descriptor(
  name='RegistrationResponse',
  full_name='drago.services.collector.RegistrationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=287,
)

_REGISTRATIONINFO.fields_by_name['network'].enum_type = _NETWORK
_REGISTRATIONINFO.fields_by_name['collection_types'].enum_type = _COLLECTIONTYPE
_REGISTRATIONINFO.fields_by_name['collection_modes'].enum_type = _COLLECTIONMODE
DESCRIPTOR.message_types_by_name['RegistrationInfo'] = _REGISTRATIONINFO
DESCRIPTOR.message_types_by_name['RegistrationResponse'] = _REGISTRATIONRESPONSE
DESCRIPTOR.enum_types_by_name['Network'] = _NETWORK
DESCRIPTOR.enum_types_by_name['CollectionType'] = _COLLECTIONTYPE
DESCRIPTOR.enum_types_by_name['CollectionMode'] = _COLLECTIONMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegistrationInfo = _reflection.GeneratedProtocolMessageType('RegistrationInfo', (_message.Message,), dict(
  DESCRIPTOR = _REGISTRATIONINFO,
  __module__ = 'manager_pb2'
  # @@protoc_insertion_point(class_scope:drago.services.collector.RegistrationInfo)
  ))
_sym_db.RegisterMessage(RegistrationInfo)

RegistrationResponse = _reflection.GeneratedProtocolMessageType('RegistrationResponse', (_message.Message,), dict(
  DESCRIPTOR = _REGISTRATIONRESPONSE,
  __module__ = 'manager_pb2'
  # @@protoc_insertion_point(class_scope:drago.services.collector.RegistrationResponse)
  ))
_sym_db.RegisterMessage(RegistrationResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\"com.qntfy.drago.services.collectorB\026DGORegistrationServiceH\001P\001Z%gitlab.qntfy.com/qcr/drago/collection\242\002\003DGO'))

_MANAGER = _descriptor.ServiceDescriptor(
  name='Manager',
  full_name='drago.services.collector.Manager',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=528,
  serialized_end=853,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='drago.services.collector.Manager.Register',
    index=0,
    containing_service=None,
    input_type=_REGISTRATIONINFO,
    output_type=_REGISTRATIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Unregister',
    full_name='drago.services.collector.Manager.Unregister',
    index=1,
    containing_service=None,
    input_type=_REGISTRATIONINFO,
    output_type=_REGISTRATIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Initialize',
    full_name='drago.services.collector.Manager.Initialize',
    index=2,
    containing_service=None,
    input_type=_REGISTRATIONINFO,
    output_type=_REGISTRATIONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MANAGER)

DESCRIPTOR.services_by_name['Manager'] = _MANAGER

# @@protoc_insertion_point(module_scope)
