# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import manager_pb2 as manager__pb2


class ManagerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Register = channel.unary_unary(
        '/drago.services.collector.Manager/Register',
        request_serializer=manager__pb2.RegistrationInfo.SerializeToString,
        response_deserializer=manager__pb2.RegistrationResponse.FromString,
        )
    self.Unregister = channel.unary_unary(
        '/drago.services.collector.Manager/Unregister',
        request_serializer=manager__pb2.RegistrationInfo.SerializeToString,
        response_deserializer=manager__pb2.RegistrationResponse.FromString,
        )
    self.Initialize = channel.unary_unary(
        '/drago.services.collector.Manager/Initialize',
        request_serializer=manager__pb2.RegistrationInfo.SerializeToString,
        response_deserializer=manager__pb2.RegistrationResponse.FromString,
        )


class ManagerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Unregister(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Initialize(self, request, context):
    """Will start SendRules to Contacting Collector
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Register': grpc.unary_unary_rpc_method_handler(
          servicer.Register,
          request_deserializer=manager__pb2.RegistrationInfo.FromString,
          response_serializer=manager__pb2.RegistrationResponse.SerializeToString,
      ),
      'Unregister': grpc.unary_unary_rpc_method_handler(
          servicer.Unregister,
          request_deserializer=manager__pb2.RegistrationInfo.FromString,
          response_serializer=manager__pb2.RegistrationResponse.SerializeToString,
      ),
      'Initialize': grpc.unary_unary_rpc_method_handler(
          servicer.Initialize,
          request_deserializer=manager__pb2.RegistrationInfo.FromString,
          response_serializer=manager__pb2.RegistrationResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'drago.services.collector.Manager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
